### ISSUE TITLE
When editing order info it's throwing an error

### ISSUE THREAD

**Issue by shravan148** [EaDesgin/Magento2-City-Dropdown#66]
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Eadesigndev\RomCity\Block\Checkout\CityUpdater::citiesJson

Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid method Eadesigndev\RomCity\Block\Checkout\CityUpdater::citiesJson
#0 /chroot/home/adde9e18/saksooka.com/html/app/code/Eadesigndev/RomCity/view/adminhtml/templates/city-admin.phtml(7): Magento\Framework\DataObject->__call('citiesJson', Array)
#1 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/chroot/home/ad...')
#2 /chroot/home/adde9e18/saksooka.com/html/vendor/magento/framework/View/Element/Template.php(270):

**Comment by AboElnoor** [comment]
I've solved this problem by changing the following line:

` class CityUpdater extends **Template** `

To 

` class CityUpdater extends **Cities** `

in the file: `app/code/Eadesigndev/RomCity/Block/Checkout/CityUpdater.php`

The error no longer happens in my project.
